import { Link } from 'react-router-dom'
import { Icon } from '../components/Icons'
import { PrototypeNotice } from '../components/PrototypeUI'
import { SafeImage } from '../components/SafeImage'

export function About() {
  return <>
    <section className="about-hero page-shell"><span className="eyebrow">Mission</span><h1>African creativity,<br/><em>without borders.</em></h1><p>FashionXpress imagines a bridge between traditional craftsmanship, digital expression, and a more globally accessible fashion culture.</p></section>
    <section className="about-image"><SafeImage width="1440" height="900" src="/images/1.jpg" alt="Editorial African fashion portrait"/><div><span>Concept rooted in Lagos</span><span>Designed for everywhere</span></div></section>
    <section className="page-shell story-grid"><div><span className="eyebrow">The product concept</span></div><div><h2>The future should remember where it came from.</h2><p>This portfolio explores how African digital fashion could preserve stories, expand independent creativity, and give people clear ways to access expressive digital pieces.</p><p>The current site demonstrates Naira pricing, digital-use licences, Virtual Try-On, Community, creator experiences, and a local Digital Wardrobe. A separate <Link className="text-link" to="/collectibles">Collectibles Lab</Link> preserves the optional educational blockchain concept without making it part of normal shopping.</p><PrototypeNotice compact>Everything shown is a product vision unless an interaction is explicitly described as local browser functionality.</PrototypeNotice></div></section>
    <section id="values" className="page-shell values"><article><b>01</b><h3>Creator-led</h3><p>Design systems should make room for a designer’s voice instead of flattening it.</p></article><article><b>02</b><h3>Progress, explained</h3><p>Emerging technology should be understandable before it asks for trust.</p></article><article><b>03</b><h3>Access with context</h3><p>Global reach matters most when culture, authorship, and usage rights remain visible.</p></article></section>
    <section className="page-shell about-cta"><div className="about-cta-visual"><SafeImage src="/images/3.jpg" alt="FashionXpress digital fashion creator concept" width="900" height="1100"/><span>Creator journey · Portfolio concept</span></div><div className="about-cta-copy"><span className="eyebrow">Explore the creator path</span><h2>Your vision<br/><em>belongs here.</em></h2><p>Walk through a local application-form demonstration and see how a future creator atelier could introduce its values without implying that intake is open.</p><div className="about-cta-actions"><Link className="button" to="/get-started">View creator prototype <Icon name="arrow" size={16}/></Link><Link className="text-link" to="/contact">Contact options <Icon name="arrow" size={16}/></Link></div><div className="about-cta-meta"><span><b>Not accepting applications</b>Demonstration only</span><span><b>No data transmitted</b>Local form experience</span></div></div></section>
  </>
}
