import { useEffect, useRef, useState } from 'react'
import { Icon } from '../components/Icons'
import { products } from '../data/products'

export function ARTryOn() {
  const videoRef = useRef(null); const streamRef = useRef(null); const [active, setActive] = useState(false); const [selected, setSelected] = useState(products[2]); const [message, setMessage] = useState(''); const [captures, setCaptures] = useState(0)
  useEffect(() => () => streamRef.current?.getTracks().forEach((track) => track.stop()), [])
  async function startCamera() { try { const stream = await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false}); streamRef.current=stream; videoRef.current.srcObject=stream; setActive(true); setMessage('Camera connected') } catch { setMessage('Camera access was unavailable. You can still select and preview a piece.') } }
  function stopCamera() { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current=null; setActive(false); setMessage('') }
  return <><section className="ar-heading page-shell"><span className="eyebrow">Experimental atelier</span><h1>Your room.<br/><em>Your runway.</em></h1><p>Select a piece, activate your camera, and explore the collection in your own space.</p></section><section className="page-shell ar-layout"><div className="camera-stage">{active ? <><video ref={videoRef} autoPlay playsInline muted/><div className="ar-overlay"><img src={selected.image} alt=""/><span>{selected.name}</span></div><div className="camera-controls"><button className="capture" onClick={() => setCaptures(captures+1)} aria-label="Capture photo"><Icon name="camera"/></button><button onClick={stopCamera}>End session</button></div></> : <div className="camera-empty"><span>AR</span><h2>Step into the frame.</h2><p>For the best result, stand in a well-lit space with your full upper body visible.</p><button className="button" onClick={startCamera}><Icon name="camera" size={17}/> Activate camera</button></div>}</div><div className="outfit-panel"><div><span className="eyebrow">The fitting rail</span><h2>Choose a look</h2></div><div className="outfit-list">{products.slice(0,4).map((p) => <button key={p.id} className={selected.id === p.id ? 'selected' : ''} onClick={() => setSelected(p)}><img src={p.image} alt=""/><span><strong>{p.name}</strong><small>{p.rarity}</small></span><i>{selected.id === p.id ? '✓' : '→'}</i></button>)}</div>{message && <p className="ar-message">{message}</p>}{captures > 0 && <p className="ar-message">{captures} {captures === 1 ? 'moment' : 'moments'} captured this session.</p>}<small className="privacy">Your camera feed stays on your device and is never uploaded.</small></div></section><section className="page-shell ar-steps"><div><b>01</b><h3>Choose a piece</h3><p>Pick from an edit of AR-ready garments.</p></div><div><b>02</b><h3>Allow camera</h3><p>Your browser will ask for permission once.</p></div><div><b>03</b><h3>Make it yours</h3><p>Move, explore, and capture the moment.</p></div></section></>
}
