import { useMemo, useState } from 'react'
import { Icon } from '../components/Icons'

const seed = [
  { id:1, title:'How do I price my first digital collection?', author:'DigitalDesigner', category:'Marketplace', replies:24, likes:42, time:'2h', text:'I’m launching ten pieces and weighing rarity, craft, and market comparison. What has worked for other creators?' },
  { id:2, title:'Blender vs Maya for fashion design', author:'3DArtist', category:'Tools', replies:18, likes:37, time:'5h', text:'Making the shift from physical to digital fashion. I’d love perspectives from artists with garment workflows in both.' },
  { id:3, title:'My “Neon Dreams” collection is live', author:'LunaCouture', category:'Showcase', replies:56, likes:89, time:'1d', text:'Six months of work, reactive materials, and a lot of iteration. Sharing the complete AR-ready collection for feedback.' },
  { id:4, title:'Making L2 minting work for small creators', author:'CryptoCreator', category:'Technology', replies:42, likes:67, time:'2d', text:'A practical breakdown of the lower-impact network choices and fee patterns I tracked over the last month.' },
]

export function Community() {
  const [threads, setThreads] = useState(seed); const [query, setQuery] = useState(''); const [liked, setLiked] = useState([]); const [composer, setComposer] = useState(false); const [draft, setDraft] = useState({title:'', text:''})
  const shown = useMemo(() => threads.filter((t) => `${t.title} ${t.author} ${t.category}`.toLowerCase().includes(query.toLowerCase())), [threads, query])
  function like(id) { if (liked.includes(id)) return; setLiked([...liked,id]); setThreads(threads.map((t) => t.id === id ? {...t, likes:t.likes+1} : t)) }
  function publish(e) { e.preventDefault(); setThreads([{id:Date.now(), title:draft.title, text:draft.text, author:'NewCreator', category:'Community', replies:0, likes:0, time:'now'}, ...threads]); setDraft({title:'',text:''}); setComposer(false) }
  return <><section className="community-hero page-shell"><span className="eyebrow">The FashionXpress circle</span><h1>Ideas look better<br/><em>in company.</em></h1><p>Ask, share, critique, and build alongside the people shaping digital fashion.</p><div className="community-actions"><label className="search"><Icon name="search"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search conversations"/></label><button className="button" onClick={() => setComposer(!composer)}><Icon name="plus" size={17}/> Start a discussion</button></div></section>{composer && <section className="page-shell"><form className="composer panel" onSubmit={publish}><div><span className="eyebrow">New discussion</span><button type="button" className="icon-button" onClick={() => setComposer(false)}><Icon name="close"/></button></div><input required placeholder="A clear, useful title" value={draft.title} onChange={(e) => setDraft({...draft,title:e.target.value})}/><textarea required rows="4" placeholder="Share your thought, question, or work…" value={draft.text} onChange={(e) => setDraft({...draft,text:e.target.value})}/><button className="button" type="submit">Publish discussion</button></form></section>}<section className="page-shell community-layout"><div><div className="feed-title"><h2>Latest discussions</h2><span>{shown.length} conversations</span></div><div className="thread-list">{shown.map((thread) => <article className="thread" key={thread.id}><div className="avatar">{thread.author[0]}</div><div><div className="thread-meta"><strong>@{thread.author}</strong><span>{thread.time}</span><i>{thread.category}</i></div><h3>{thread.title}</h3><p>{thread.text}</p><div className="thread-actions"><span>◯ {thread.replies} replies</span><button className={liked.includes(thread.id) ? 'liked' : ''} onClick={() => like(thread.id)}><Icon name="heart" size={16}/> {thread.likes}</button></div></div></article>)}</div></div><aside className="community-side"><div className="side-card"><span className="eyebrow">Coming up</span><h3>Virtual Fashion Week</h3><p>Live showcases from designers across the continent.</p><b>15 · OCT · 2026</b><button className="button ghost full">Save my seat</button></div><div className="side-card resources"><h3>Creator resources</h3><a href="#academy">Academy <span>↗</span></a><a href="#api">API documentation <span>↗</span></a><a href="#guidelines">Community guidelines <span>↗</span></a></div></aside></section></>
}
