import { Link } from 'react-router-dom'
import { Icon } from '../components/Icons'
import { Newsletter, SectionHeading } from '../components/Layout'
import { ProductCard } from '../components/ProductCard'
import { products } from '../data/products'

export function Home({ onAdd }) {
  return <>
    <section className="hero page-shell"><div className="hero-copy"><span className="eyebrow"><Icon name="spark" size={15}/> Digital fashion, made human</span><h1>Wear the<br/><em>impossible.</em></h1><p>Collect boundary-pushing digital couture from Africa’s new generation of creators—and make every virtual space your runway.</p><div className="button-row"><Link className="button" to="/collections">Explore the drop <Icon name="arrow" size={17}/></Link><Link className="text-link" to="/about">Discover our world <Icon name="arrow" size={16}/></Link></div><div className="stats"><div><strong>50k+</strong><span>Creators</span></div><div><strong>500k</strong><span>Digital pieces</span></div><div><strong>48</strong><span>Countries</span></div></div></div><div className="hero-art"><div className="hero-frame"><img src="/images/hero-model.jpg" alt="Digital couture model"/></div><span className="floating-note note-one">01 / Genesis drop</span><span className="floating-note note-two">Made beyond matter</span></div></section>
    <section className="marquee" aria-label="FashionXpress features"><div>AI CURATION <i>✦</i> AR TRY-ON <i>✦</i> VERIFIED EDITIONS <i>✦</i> GLOBAL CREATORS <i>✦</i> AI CURATION <i>✦</i> AR TRY-ON</div></section>
    <section className="page-shell section"><SectionHeading eyebrow="New expressions" title="The genesis collection." copy="A limited edit of six pieces, each authored for a world without physical limits."/><div className="product-grid featured-products">{products.slice(0, 3).map((p) => <ProductCard key={p.id} product={p} onAdd={onAdd}/>)}</div><Link className="text-link section-link" to="/collections">View the full collection <Icon name="arrow" size={16}/></Link></section>
    <section className="manifesto"><div className="manifesto-image"><img src="/images/creators.jpg" alt="Fashion creator at work"/></div><div className="manifesto-copy"><span className="eyebrow">Built for expression</span><h2>Culture is not a trend. It’s our source code.</h2><p>We give independent designers the technology, reach, and ownership to build lasting worlds around their work.</p><div className="mini-grid"><div><b>01</b><h3>Create freely</h3><p>Tools that expand your craft, without flattening your voice.</p></div><div><b>02</b><h3>Own completely</h3><p>Transparent editions and provenance made simple.</p></div></div><Link className="button ghost" to="/get-started">Become a creator <Icon name="arrow" size={16}/></Link></div></section>
    <section className="page-shell section journey"><SectionHeading eyebrow="One world, many doors" title="Choose your experience." align="center"/><div className="journey-grid"><Link to="/ar-tryon" className="journey-card large"><img src="/images/ar.jpg" alt="Augmented reality fashion"/><span>For collectors</span><h3>Try on a new reality.</h3><i><Icon name="arrow"/></i></Link><Link to="/community" className="journey-card"><img src="/images/community.jpg" alt="Fashion community"/><span>For community</span><h3>Find your people.</h3><i><Icon name="arrow"/></i></Link><Link to="/get-started" className="journey-card light"><span>For creators</span><h3>Build the next fashion house.</h3><p>Bring your vision. We’ll bring the infrastructure.</p><i><Icon name="arrow"/></i></Link></div></section>
    <div className="page-shell"><Newsletter/></div>
  </>
}
